org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Minecraft Properties
minecraft_version = 26.1-rc-2
minecraft_version_supported = [26.1-rc-2]
minecraft_version_filter = snapshots
minecraft_version_lower = 1.21.11
minecraft_version_upper =

# File Name
minecraft_version_name = 26.1
archives_base_name = MoreComposterVariants

## Mod Properties

mod_id=lolmcmv
mod_name=More Composter Variants
mod_name_short=More Composter Variants
mod_license=MIT
mod_version=1.8.2
mod_group_id=com.pnku.mcmv
mod_author=pnku
mod_description=Adding composter variants to Minecraft

# Dependencies
quad_version=1.2.0
nemos_woodcutter_version=1.12.1-1.21.3